"""change job index

Revision ID: 586052a4dcf5
Revises: 6f5e8fba7050
Create Date: 2023-04-24 14:52:24.050986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586052a4dcf5'
down_revision = '6f5e8fba7050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
