version: '3'
services:
    redis:
        image: redis:4.0.6-alpine
        ports:
          - "6379:6379"
        volumes:
            - redis_data:/redis

    flask-app:
        image: app-image
        container_name: flask-app
        build: .
        platform: linux/amd64
        restart: always
        depends_on:
            - redis
        ports:
            - '5000:5000'
        volumes:
            - simulations:/usr/src/app/simulations

    worker:
        image: app-image:latest
        platform: linux/amd64
        depends_on:
            - redis
        command: rq worker submission-tasks --url redis://redis:6379
        links:
            - redis
        volumes:
            - simulations:/usr/src/app/simulations

volumes:
    simulations:
    redis_data: